---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/unnamed (1)/unnamed (1).png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/299755/articles/447214/master/file/figures/unnamed%20(1)/unnamed%20(1).png"
    folder_url: "/users/299755/articles/447214/master/folder/figures/unnamed (1)"
